services:
  mongodb:
    image: mongo:8.0.5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
#    command: mongod  --port 27016
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:secret@mongodb:27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234567
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8079:8081
    networks:
      - mongo-network

networks:
  mongo-network:
    name: mongo-network
    driver: bridge

volumes:
  mongo:
  postgres:
