# Config server
spring:
  application:
    name: api-gateway
server:
  port: 9000

# Springdoc using openapi through swagger ui

springdoc:
  api-docs:
    path: /api-docs # Custom path for /v3/api-docs (default)
  swagger-ui:
    path: /swagger-ui.html # Custom path for /swagger-ui/index.html (default)
    urls:
      - name: Product Service
        url : /aggregate/product-service/api-docs
      - name: Order Service
        url: /aggregate/order-service/api-docs


management:
  endpoints:
    web:
      exposure:
        include: gateway
#logging:
#  level:
#    reactor:
#      netty: DEBUG
#    org:
#      springframework:
#        cloud:
#          gateway: DEBUG
#


