# Config server
spring:
  application:
    name: api_gateway
  config:
    import: optional:configserver:http://localhost:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-microservices-security-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: spring-boot-microservices-client
      principle-attribute: preferred_username

# Springdoc using openapi through swagger ui
springdoc:
  api-docs:
    path: /api-docs # Custom path for /v3/api-docs (default)
  swagger-ui:
    path: /swagger-ui.html # Custom path for /swagger-ui/index.html (default)
    urls:
      - name: Product Service
        url : /aggregate/product-service/api-docs
      - name: Order Service
        url: /aggregate/order-service/api-docs
      - name: User Service
        url: /aggregate/user-service/api-docs
      - name: Supplier Service
        url: /aggregate/supplier-service/api-docs
      - name: Coupon Service
        url: /aggregate/coupon-service/api-docs
      - name: Consumer Service
        url: /aggregate/consumer-service/api-docs


management:
  endpoints:
    web:
      exposure:
        include: gateway




#logging:
#  level:
#    reactor:
#      netty: DEBUG
#    org:
#      springframework:
#        cloud:
#          gateway: DEBUG
#


