spring:
  data:
    mongodb:
      uri: mongodb+srv://phucdang01235:Pd3Fim8yd3aPPadd@dangthanhphuc.jqh3y.mongodb.net/?retryWrites=true&w=majority&appName=dangthanhphuc
      database: supplier-service

server:
  port: 8083

# Springdoc using openapi through swagger ui
springdoc:
  api-docs:
    path: /api-docs